name: toneharbor
description: "ToneHarbor · Your music, all in harbor."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  rhttp: ^0.15.0
  media_kit:
    git:
      url: https://git.nxcloud.club:12750/LyricTracers/media-kit.git
      ref: main
      path: media_kit
  media_kit_libs_audio: ^1.0.7
  flutter_context_menu: 
    git:
      url: https://git.nxcloud.club:12750/LyricTracers/flutter_context_menu.git
      ref: main
  audio_service: ^0.18.18
  audio_session: ^0.2.3
  smtc_windows: ^1.1.0
  open_file: ^3.5.10
  flutter_riverpod: ^3.1.0
  hooks_riverpod: ^3.1.0
  flutter_hooks: ^0.21.3
  fading_edge_scrollview: ^4.1.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10
  path: ^1.9.0
  path_provider: ^2.1.4
  go_router: ^17.0.1 
  shared_preferences: ^2.5.4
  sqlite3: 2.9.4
  sqlite3_flutter_libs: 0.5.41
  freezed_annotation: ^3.0.0
  json_annotation: 4.9.0
  riverpod_annotation: ^4.0.0
  material_color_utilities: ^0.11.1
  logger: ^2.6.2
  synchronized: ^3.1.0
  file_picker: ^10.3.10
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  metadata_god: 
    git:
      url: https://git.nxcloud.club:12750/LyricTracers/metadata_god.git
      ref: main
  file: ^7.0.1
  drift: 2.29.0
  mime: ^2.0.0
  collection: any
  flutter_broadcasts:
    git:
      url: https://github.com/KRTirtho/flutter_broadcasts.git
      ref: 63931dfe06733d4fb7452e9981e1f0b23414d97a
  package_info_plus: ^9.0.0
  archive_gbk:
    git:
      url: https://git.nxcloud.club:12750/LyricTracers/archive_gbk.git
      ref: main
  lyricskit:
    git:
      url: https://git.nxcloud.club:12750/LyricTracers/lyricskit.git
      ref: main
  tray_manager:
    git:
      url: https://git.nxcloud.club:12750/LyricTracers/tray_manager.git
      ref: main
  window_manager:
    git:
      url: https://git.nxcloud.club:12750/LyricTracers/window_manager.git
      ref: main 
  flutter_native_splash:
    git:
      url: https://git.nxcloud.club:12750/LyricTracers/flutter_native_splash.git
      ref: main
  flutter_lyric:
    git:
      url: https://git.nxcloud.club:12750/LyricTracers/flutter_lyric.git
      ref: main
  connectivity_plus: 7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: 2.7.1
  freezed: ^3.2.3
  drift_dev: 2.29.0
  json_serializable: 6.11.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/

flutter_native_splash:
  color: "#F8F6F0"
  window_width: 1230
  window_height: 780
  window_minimum_width: 1230  
  window_minimum_height: 780
  window_button_visibility: true
  skip_taskbar: false
  center: true
  hide_titlebar: true
  animation_type: audioEqualizer
  animation_color: "#4A5859"
  text: "「拾音坞｜一坞藏万乐，双耳遇知音」"
  text_color: "#4A5859"
